name: Spawn
version: 1.0.3
main: io.papermc.spawn.Main
description: Spawn plugin
author: pairnon
website: https://github.com/pairnon/Spawn
api-version: '1.20'
commands:
  setspawn:
    description: Set server spawn point
    usage: setspawn
  setwarnradius:
    description: Set warning radius in blocks from spawn
    usage: setwarnradius <blocks>
  removewarnradius:
    description: Remove the spawn warning radius
    usage: removewarnradius
  spawn:
    description: Teleport to spawn
    usage: spawn
  rtp:
    description: Teleport to random location
    usage: rtp
    aliases: [wild]
  setrtpradius:
    description: Set /rtp radius in blocks from spawn
    usage: setrtpradius <blocks>
  setteleportcooldown:
    description: Set teleport cooldown in seconds
    usage: setteleportcooldown <seconds>
  getspawnconfig:
    description: Get plugin configuration
    usage: getspawnconfig