name: Spawn
version: 1.0.2
main: io.papermc.spawn.Main
description: Spawn plugin
author: pairnon
website: https://github.com/pairnon/Spawn
api-version: '1.20'
commands:
  setspawn:
    description: Set server spawn point
    usage: setspawn
  setwarnradius:
    description: Set warning radius in blocks from spawn
    usage: setwarnradius <blocks>
  removewarnradius:
    description: Remove the spawn warning radius
    usage: removewarnradius
  spawn:
    description: Teleport to spawn
    usage: spawn
  wild:
    description: Teleport to random location
    usage: wild
    aliases: [rtp]
  setwildradius:
    description: Set /wild radius in blocks from spawn
    usage: setwildradius <blocks>