name: Spawn
version: 1.1.0
main: io.papermc.spawn.Main
description: Spawn plugin
author: pairnon
website: https://github.com/pairnon/Spawn
api-version: '1.20'
commands:
  setspawn:
    description: Set server spawn point
    usage: setspawn
  warnradius:
    description: Configure warning radius in blocks from spawn
    usage: warnradius <blocks>
  disablespawnwarn:
    description: Disable spawn region warning
    usage: disablespawnwarn
  spawn:
    description: Teleport to spawn
    usage: spawn
  rtp:
    description: Teleport to random location
    usage: rtp
    aliases: [wild]
  rtpradius:
    description: Configure /rtp radius in blocks from spawn
    usage: rtpradius <blocks>
  teleportcooldown:
    description: Configure teleport cooldown in seconds
    usage: teleportcooldown <seconds>
  spawnconfig:
    description: Get plugin configuration
    usage: spawnconfig