name: Spawn
version: 1.0.1
main: io.papermc.spawn.Main
description: Spawn plugin
author: pairnon
website: https://github.com/pairnon/Spawn
api-version: '1.20'
commands:
  setspawn:
    description: Set server spawn point
    usage: setspawn
  setwarnradius:
    description: Set warning radius in blocks from spawn
    usage: setwarnradius
  spawn:
    description: Teleport to spawn
    usage: spawn